import {WEAPONS,weaponFor} from './weapons.js?v=6';
import {END,CHECKPOINTS,ENCOUNTERS} from './journey.js?v=6';
export const RULES={end:END,speed:4.1,parryWindow:.48,guardCooldown:.8};
export function createGame(s=null){const cp=CHECKPOINTS[s?.checkpoint]||CHECKPOINTS[0];return {hero:{x:0,z:cp.z,hp:130,stamina:100,guard:false,guardHeld:false,guardPending:false,parry:0,guardCooldown:0,attack:0,attackHit:false,attackId:0,attackWeapon:null,attackAimX:0,attackAimZ:1,dodge:0,dodgeX:0,dodgeZ:0,hurt:0},enemy:null,round:cp.round,kills:cp.round,checkpoint:cp,camps:s?.camps||[],rewarded:s?.rewarded||[],coins:s?.coins||0,owned:s?.owned||['sword'],equipped:s?.equipped||'sword',upgrades:s?.upgrades||[],auto:false,paused:true,status:'playing',time:0,events:[]};}
function emit(g,type,extras={}){g.events.push({type,...extras});}
export function clearControls(g){g.auto=false;g.hero.guard=false;g.hero.guardHeld=false;g.hero.guardPending=false;g.hero.parry=0;}
export function setPaused(g,p){g.paused=p;if(p)clearControls(g);}
export function canShop(g){return g.status==='playing'&&!g.enemy&&CHECKPOINTS.some(cp=>g.round>=cp.round&&Math.abs(g.hero.z-cp.z)<3.2);}
export function buy(g,id){const w=WEAPONS[id];if(!canShop(g)||!w||g.owned.includes(id)||g.coins<w.cost)return false;g.coins-=w.cost;g.owned.push(id);g.equipped=id;emit(g,'equipment');emit(g,'save');return true;}
export function equip(g,id){if(!canShop(g)||!g.owned.includes(id))return false;g.equipped=id;emit(g,'equipment');emit(g,'save');return true;}
export function upgrade(g,id=g.equipped){const w=WEAPONS[id];if(!canShop(g)||!w||!g.owned.includes(id)||g.upgrades.includes(id)||g.coins<w.upgradeCost)return false;g.coins-=w.upgradeCost;g.upgrades.push(id);emit(g,'upgrade',{id});emit(g,'save');return true;}
export function retry(g){Object.assign(g,createGame({checkpoint:g.checkpoint.id,camps:g.camps,rewarded:g.rewarded,coins:g.coins,owned:g.owned,equipped:g.equipped,upgrades:g.upgrades}));emit(g,'retry');emit(g,'save');return g;}
export function guard(g,down){const h=g.hero;if(!down){h.guardHeld=false;h.guardPending=false;h.guard=false;return;}if(g.paused||g.status!=='playing')return;const fresh=!h.guardHeld;h.guardHeld=true;if(h.dodge>0||h.attack>0){h.guardPending=true;return;}if(h.guard)return;h.guard=true;h.guardPending=false;if(fresh&&h.guardCooldown<=0&&h.stamina>=18){h.stamina-=18;h.parry=.48;h.guardCooldown=.8;emit(g,'guard');}}
export function attack(g){const h=g.hero,w=weaponFor(g);if(g.paused||g.status!=='playing'||h.attack>0||h.dodge>0||h.stamina<w.stamina)return false;h.attack=w.windup+w.recover;h.attackWeapon=w;const ax=g.enemy?g.enemy.x-h.x:0,az=g.enemy?g.enemy.z-h.z:1,an=Math.max(.001,Math.hypot(ax,az));h.attackAimX=ax/an;h.attackAimZ=az/an;h.attackHit=false;h.attackId++;h.stamina-=w.stamina;h.guard=false;h.guardPending=h.guardHeld;h.parry=0;emit(g,'swing',{weapon:w.id});return true;}
export function dodge(g,x=0,z=0){const h=g.hero;if(g.paused||g.status!=='playing'||h.dodge>0||h.attack>.36||h.stamina<23)return false;if(Math.hypot(x,z)<.15){x=h.x>0?-1:1;z=0;}const n=Math.hypot(x,z);h.dodgeX=x/n;h.dodgeZ=z/n;h.dodge=.48;h.stamina-=23;h.attack=0;h.attackWeapon=null;h.attackHit=true;h.guard=false;h.guardPending=h.guardHeld;h.parry=0;emit(g,'dodge');return true;}
function kill(g){const e=g.enemy,fresh=!g.rewarded.includes(e.id);if(fresh){g.coins+=e.boss?60:30;g.rewarded.push(e.id);}g.round++;g.kills=g.round;g.hero.hp=Math.min(130,g.hero.hp+8);g.hero.stamina=100;emit(g,'kill',{x:e.x,z:e.z,reward:fresh?(e.boss?60:30):0});g.enemy=null;emit(g,'save');emit(g,g.round<9?'cleared':'gate');}
function windup(g,e){if(e.boss){e.pattern=e.sequence%2===0?'pesado':'investida';e.windup=e.pattern==='pesado'?1.3:.9;e.sequence++;}e.phase='windup';e.timer=e.windup;e.aimX=g.hero.x;e.aimZ=g.hero.z;e.attackHit=false;emit(g,'tell',{pattern:e.pattern});}
export function step(g,delta,m={x:0,z:0}){if(g.paused||g.status!=='playing')return;const dt=Math.max(0,Math.min(delta,1/30));g.time+=dt;const h=g.hero;h.parry=Math.max(0,h.parry-dt);h.guardCooldown=Math.max(0,h.guardCooldown-dt);h.hurt=Math.max(0,h.hurt-dt);const before=h.attack;h.attack=Math.max(0,h.attack-dt);h.stamina=Math.min(100,h.stamina+dt*(h.guard?12:h.attack>0||h.dodge>0?0:27));let x=m.x||0,z=m.z||0;if(z<-.12)g.auto=false;if(g.auto&&z>=-.12)z=1;const n=Math.max(1,Math.hypot(x,z));x/=n;z/=n;
if(h.dodge>0){h.x+=h.dodgeX*dt*9;h.z+=h.dodgeZ*dt*9;h.dodge=Math.max(0,h.dodge-dt);}else{const speed=4.1*(h.guard?.5:h.attack>0?.3:1);h.x+=x*dt*speed;h.z+=z*dt*speed;}if(h.guardHeld&&h.guardPending&&h.attack<=0&&h.dodge<=0){h.guard=true;h.guardPending=false;}h.x=Math.max(-3.3,Math.min(3.3,h.x));h.z=Math.max(0,Math.min(g.round<9?ENCOUNTERS[g.round].z+3.2:END,h.z));
for(const cp of CHECKPOINTS.slice(1)){if(g.checkpoint.id<cp.id&&g.round>=cp.round&&h.z>=cp.z){g.checkpoint=cp;g.auto=false;h.x=0;h.z=cp.z;if(!g.camps.includes(cp.id)){g.camps.push(cp.id);h.hp=130;h.stamina=100;}emit(g,'checkpoint',{name:cp.name});emit(g,'save');}}
if(!g.enemy&&g.round<9&&h.z>=ENCOUNTERS[g.round].z-6){const r=ENCOUNTERS[g.round];g.enemy={...r,x:g.round%2?1:-.5,maxHp:r.hp,phase:'approach',timer:.5,attackHit:false,aimX:h.x,aimZ:h.z,hurt:0,sequence:0};emit(g,'encounter',{name:r.label});if(g.auto){g.auto=false;emit(g,'autoStop');}}
const e=g.enemy;if(e){e.hurt=Math.max(0,e.hurt-dt);const dx=h.x-e.x,dz=h.z-e.z,dist=Math.hypot(dx,dz),w=h.attackWeapon;if(w&&before>w.recover&&h.attack<=w.recover&&!h.attackHit){h.attackHit=true;if(dist<=w.reach&&-(dx*h.attackAimX+dz*h.attackAimZ)>-.2&&Math.abs(dx*h.attackAimZ-dz*h.attackAimX)<w.width){e.hp-=w.damage;e.hurt=.22;emit(g,'hit',{x:e.x,z:e.z,weapon:w.id});if(w.id==='hammer'&&e.phase!=='strike'){e.timer=e.phase==='stunned'?Math.max(e.timer,.55):.55;e.phase='stunned';}if(e.hp<=0){kill(g);return;}}else emit(g,'miss');}
e.timer-=dt;if(e.phase==='approach'){if(dist>1.8){e.x+=dx/dist*dt*(e.pattern==='investida'?2.65:2.1);e.z+=dz/dist*dt*2.3;}if(dist<2.2&&e.timer<=0)windup(g,e);}else if(e.phase==='windup'){if(e.pattern==='investida'){const n=Math.max(.01,dist);e.x-=dx/n*dt*.65;e.z-=dz/n*dt*.65;}if(e.timer<=0){e.phase='strike';e.timer=.27;emit(g,'enemySwing');}}
else if(e.phase==='strike'){if(e.pattern==='investida'&&e.timer>.12){const ax=e.aimX-e.x,az=e.aimZ-e.z,n=Math.max(.01,Math.hypot(ax,az));e.x+=ax/n*dt*9;e.z+=az/n*dt*9;}if(e.timer<=.12&&!e.attackHit){e.attackHit=true;const range=Math.hypot(h.x-e.x,h.z-e.z)<(e.pattern==='pesado'?3.1:2.65),aim=Math.hypot(h.x-e.aimX,h.z-e.aimZ)<(e.pattern==='pesado'?2.8:1.8);if(range&&aim&&h.dodge<=0){if(h.parry>0){e.phase='stunned';e.timer=1.55;e.hp-=12;h.stamina=Math.min(100,h.stamina+22);h.parry=0;emit(g,'parry',{x:(e.x+h.x)/2,z:(e.z+h.z)/2});if(e.hp<=0){kill(g);return;}}else if(h.guard&&h.stamina>=22){h.stamina-=22;emit(g,'block',{x:h.x,z:h.z});}else{h.hp-=e.damage;h.hurt=.4;if(h.guard){h.guard=false;h.stamina=0;emit(g,'guardBreak');}emit(g,'damage',{x:h.x,z:h.z});if(h.hp<=0){g.status='dead';clearControls(g);emit(g,'dead');emit(g,'save');return;}}}else emit(g,'evade');}if(e.timer<=0&&e.phase==='strike'){e.phase='recover';e.timer=e.pattern==='pesado'?1.25:.95;}}
else if(e.timer<=0){e.phase='approach';e.timer=.2;}e.x=Math.max(-3.5,Math.min(3.5,e.x));}
if(g.round===9&&h.z>=END-.15){g.status='won';clearControls(g);emit(g,'won');emit(g,'save');}}
